
event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

search:
    resource: "@SearchBundle/Resources/config/routing.yml"
    prefix:   /search

ldap:
    resource: "@LDAPBundle/Resources/config/routing.yml"
    prefix:   /system/ldap

fos_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

system:
    resource: "@SystemBundle/Resources/config/routing.yml"
    prefix:   /


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /groups

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
#    resource: "@AppBundle/Resources/config/routing.yml"
