
event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

search:
    resource: "@SearchBundle/Resources/config/routing.yml"
    prefix:   /search

ldap:
    resource: "@LDAPBundle/Resources/config/routing.yml"
    prefix:   /system/ldap

system:
    resource: "@SystemBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
#    resource: "@AppBundle/Resources/config/routing.yml"
