# app/config/security.yml
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#        SystemBundle\Entity\User: md5
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check

            logout:
                path:   /logout
                target: /

    #В примере выше, пользователь с ролью ROLE_ADMIN будет также иметь роль ROLE_USER.
    #Роль ROLE_SUPER_ADMIN включает в себя ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, и ROLE_USER
    #(унаследовав её от ROLE_ADMIN).
    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    access_control:
            - { path: ^/security, roles: ROLE_ADMIN }
            - { path: ^/admin, roles: ROLE_ADMIN }

    acl:
        connection: default