services:
#    system.example:
#        class: SystemBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    sonata.admin.user:
        class: SystemBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
        arguments:
            - ~
            - SystemBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]