<?php

namespace LDAPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddressLinkTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressLinkTypeRepository extends EntityRepository
{
}
